language: node_js
node_js: 
  - '10'
before_install:
  - rm -rf node_modules
  - zip -r app *
  - mkdir -p deploy
  - mv app.zip deploy/app.zip
deploy:
  # aws S3
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET_NAME
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: KimPinot/node-travis-ci-cd
      branch: production
  # aws CodeDeploy
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET_NAME
    key: app.zip
    bundle_type: zip
    application: pinot-ci-cd-app
    deployment_group: pinot-ci-cd-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: KimPinot/node-travis-ci-cd
      branch: production
branches:
  only:
    - production